name: Build CNPG Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag or branch that will be used as the base image for the CNPG Operator (default: v1.25.0 )"
        required: false
        default: "v1.25.0"

jobs:
  build-cnpg:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout CNPG Repository
        uses: actions/checkout@v4
        with:
          repository: 'cloudnative-pg/cloudnative-pg'
          ref: ${{ github.event.inputs.tag }}
          path: 'cloudnative-pg'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.GHACTIONQUAYNAME }}
          password: ${{ secrets.GHACTIONQUAYTOKEN }}

      - name: Patch CNPG Repository
        run: |
          cd cloudnative-pg
          find . -name .git -a -type d -prune -o -type f -exec sed -i -e 's|postgresql.cnpg.io|postgresql.cnpg.noobaa.io|g' -e 's|postgresql-cnpg-io|postgresql-cnpg-noobaa-io|g' {} +

      - name: Bake and Build Image
        uses: docker/bake-action@v4
        with:
          files: cloudnative-pg/docker-bake.hcl
          targets: default
          set: |
            *.tags=quay.io/noobaa/cloudnative-pg-noobaa:${{ github.event.inputs.tag }}
          workdir: cloudnative-pg

      - name: Push CNPG Image to Quay
        run: docker push quay.io/noobaa/cloudnative-pg-noobaa:${{ github.event.inputs.tag }}
